#ifndef ADAS_MGM__SRC__GENERATED_ADAPTER_HPP_
#define ADAS_MGM__SRC__GENERATED_ADAPTER_HPP_

#include "core/mgm_types.hpp"

namespace adas_mgm
{

// Adapter for the non-reentrant two-state ERT global API generated by Simulink.
// Use one instance in one thread. The production ROS node continues to use
// the four-state mgm_core; this adapter verifies only the documented shared
// LANE/WAYPOINT subset.
class GeneratedMgmAdapter
{
public:
  explicit GeneratedMgmAdapter(const CoreParams & params);
  GeneratedMgmAdapter(const GeneratedMgmAdapter &) = delete;
  GeneratedMgmAdapter & operator=(const GeneratedMgmAdapter &) = delete;

  void reset(const CoreParams & params);
  CoreOutput step(const CoreSnapshot & input);
};

}  // namespace adas_mgm

#endif  // ADAS_MGM__SRC__GENERATED_ADAPTER_HPP_
