#ifndef ADAS_MGM__SRC__GENERATED_ADAPTER_HPP_
#define ADAS_MGM__SRC__GENERATED_ADAPTER_HPP_

#include <mutex>
#include <thread>

#include "core/mgm_types.hpp"

namespace adas_mgm
{

// Adapter for the non-reentrant four-state ERT global API generated by Simulink.
// Exactly one instance may exist in a process. Its first public step/reset call
// binds an owning thread and all later calls must use that thread. Construction
// does not bind so a ROS executor may construct it before a dedicated 10 ms
// loop thread starts. ADAS_MGR2 v1.88 covers LANE/WAYPOINT/AVOID/PARKING, but
// does not contain the newer production rear-escape extension. The adapter
// also normalizes v1.88's legacy stale-frame extrapolation to the current
// sample-to-sample reference hold contract without modifying generated files.
class GeneratedMgmAdapter
{
public:
  explicit GeneratedMgmAdapter(const CoreParams & params);
  ~GeneratedMgmAdapter() noexcept;

  GeneratedMgmAdapter(const GeneratedMgmAdapter &) = delete;
  GeneratedMgmAdapter & operator=(const GeneratedMgmAdapter &) = delete;
  GeneratedMgmAdapter(GeneratedMgmAdapter &&) = delete;
  GeneratedMgmAdapter & operator=(GeneratedMgmAdapter &&) = delete;

  void reset(const CoreParams & params);
  CoreOutput step(const CoreSnapshot & input);

  // 모델 내부 히스테리시스 카운터 (ADAS_MGR2_DW) — **관찰 전용**.
  // 전이 이유 로깅이 레퍼런스 코어와 같은 값을 쓸 수 있게 하기 위한 것이며,
  // 모델로 되먹임되는 경로는 없다.
  int32_t laneLowCnt() const;
  int32_t laneHighCnt() const;
  int32_t avoidTicks() const;
  int32_t returnHoldLeft() const;
  bool stopZoneHolding() const;
  int32_t stopHoldLeft() const;

private:
  void initialize(const CoreParams & params);
  void requireOwningThread(const char * operation);
  void releaseLease() noexcept;

  std::mutex owner_mutex_;
  std::thread::id owner_thread_{};
  bool owner_thread_bound_{false};
  bool lease_acquired_{false};
};

}  // namespace adas_mgm

#endif  // ADAS_MGM__SRC__GENERATED_ADAPTER_HPP_
