#ifndef ADAS_MGM__SRC__GENERATED_ADAPTER_HPP_
#define ADAS_MGM__SRC__GENERATED_ADAPTER_HPP_

#include <mutex>
#include <thread>

#include "core/mgm_types.hpp"

namespace adas_mgm
{

// Adapter for the non-reentrant two-state ERT global API generated by Simulink.
// Exactly one instance may exist in a process. Its first public step/reset call
// binds an owning thread and all later calls must use that thread. Construction
// does not bind so a ROS executor may construct it before a dedicated 10 ms
// loop thread starts. The generated model covers only the documented shared
// LANE/WAYPOINT subset.
class GeneratedMgmAdapter
{
public:
  explicit GeneratedMgmAdapter(const CoreParams & params);
  ~GeneratedMgmAdapter() noexcept;

  GeneratedMgmAdapter(const GeneratedMgmAdapter &) = delete;
  GeneratedMgmAdapter & operator=(const GeneratedMgmAdapter &) = delete;
  GeneratedMgmAdapter(GeneratedMgmAdapter &&) = delete;
  GeneratedMgmAdapter & operator=(GeneratedMgmAdapter &&) = delete;

  void reset(const CoreParams & params);
  CoreOutput step(const CoreSnapshot & input);

private:
  void initialize(const CoreParams & params);
  void requireOwningThread(const char * operation);
  void releaseLease() noexcept;

  std::mutex owner_mutex_;
  std::thread::id owner_thread_{};
  bool owner_thread_bound_{false};
  bool lease_acquired_{false};
};

}  // namespace adas_mgm

#endif  // ADAS_MGM__SRC__GENERATED_ADAPTER_HPP_
